"use client";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "./components/style.css";
export default function Home() {
  const [num1, setNum1] = useState(0);
  const [num2, setNum2] = useState(0);
  const [result, setResult] = useState(0);
  const add = () => {
    setResult(parseInt(num1) + parseInt(num2));
  };
  const subtract = () => {
    setResult(parseInt(num1) - parseInt(num2));
  };
  const multiply = () => {
    setResult(parseInt(num1) * parseInt(num2));
  };
  const divide = () => {
    setResult(parseInt(num1) / parseInt(num2));
  };
  return (
    <div className="px-8 flex flex-col items-center justify-center h-screen bg-gray-900 text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl font-bold mb-4" data-testid="result">
        {result}
      </div>
      <input
        type="number"
        className="my-2 px-2 py-1 text-lg w-52 bg-gray-900 border border-gray-600 text-white rounded-lg"
        data-testid="num1"
        value={num1}
        onChange={(e) => setNum1(e.target.value)}
      />
      <input
        type="number"
        className="my-2 px-2 py-1 text-lg w-52 bg-gray-900 border border-gray-600 text-white rounded-lg"
        data-testid="num2"
        value={num2}
        onChange={(e) => setNum2(e.target.value)}
      />
      <button
        onClick={add}
        className="text-lg p-2 w-52 my-2 border border-black bg-black rounded-lg text-white"
        data-testid="add"
      >
        Add
      </button>
      <button
        onClick={subtract}
        className="text-lg p-2 w-52 my-2 border border-black bg-black rounded-lg text-white"
        data-testid="subtract"
      >
        Subtract
      </button>
      <button
        onClick={multiply}
        className="text-lg p-2 w-52 my-2 border border-black bg-black rounded-lg text-white"
        data-testid="multiply"
      >
        Multiply
      </button>
      <button
        onClick={divide}
        className="text-lg p-2 w-52 my-2 border border-black bg-black rounded-lg text-white"
        data-testid="divide"
      >
        Divide
      </button>
    </div>
  );
}
